# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = var.region
  default_tags {
    tags = {
      Environment = "ecs-terragrunt-deployment"
      Project     = "nestjs-app"
      ManagedBy   = "Terraform"
    }
  }
}
